# SNValue Merge + Phenotype Annotation Pipeline

**Purpose.** Reproduce the `3_16_26_manual_annotation.csv` output format starting from the two new raw files:
- `SNValueQuery_398645_20250528_20260528 (1).csv`
- `SNValueQuery_401430_20250528_20260528 (1).csv`

by (1) row-stacking the two files and (2) applying the logics from `phenotype.ipynb`.

**User-confirmed decisions (do not change without asking):**
1. **Merge = vertical stack** (row-concatenate, align on the shared 8 columns).
2. **Derivations:** `breeding_date = date_collected − DSLB days`; `combined_cow = CowID.0ClientID.0` (e.g. `1 + 392159 → 1.0392159.0`). Verified against `unique_combination_cleaned.csv` (e.g. `3/4/2022 − 35 = 1/28/2022`).
3. **Breeding-event clustering = phenotype Cell 7:** group by `(combined_cow, year, month)`, `day.diff() >= 2` starts a new event. `adj_final_breeding = min(breeding_date)` per cluster; `breed_event_id = cow_year_month` (single cluster) or `cow_year_month_cluster` (multi-cluster) — faithful to Cell 7.
4. **`final_resolved` = phenotype Cell 54** (latest fixed `resolve_cow_history` with chronological breed events, gap `<300` rebred overrides, single-sample rebred fixes, last-event handling, including the `Pregant_with_rc` spelling).
5. **`first_sample_rc`, `rc_resolved_open` left blank/NaN**; missing `Date Received/Sent/Approved`, `ProjectNo` left as NaN (new raw files do not contain them).

**Pipeline output:** `merged_annotation_output.csv` with the exact 23-column order of `3_16_26_manual_annotation.csv`.

**Performance note:** the literal Cell-7 Python loop over ~11k `(cow, year, month)` groups takes >60 s and the per-cow `groupby.apply` resolve takes ~100 s. This notebook therefore implements **vectorized equivalents with identical semantics** (documented inline) so the full run finishes in ~100 s instead of timing out. The original loop code is quoted in comments for traceability.

## 0. Imports & paths

In [19]:
import time
import numpy as np
import pandas as pd

T0 = time.time()
def log(msg):
    print(f"[{time.time()-T0:.1f}s] {msg}", flush=True)

F1 = '/home/rajesh/work/ornella/SNValueQuery_398645_20250528_20260528 (1).csv'
F2 = '/home/rajesh/work/ornella/SNValueQuery_401430_20250528_20260528 (1).csv'
MANUAL_REF = '/home/rajesh/work/ornella/3_16_26_manual_annotation.csv'
OUT = '/home/rajesh/work/ornella/merged_annotation_output.csv'

## Step 1 — Merge the two SNValue files (row-stack)

Both raw files share the same 8 columns (`Date Collected, CowID, ClientID, Test, Result, S-N Value, DIM, DSLB`) for different `ClientID`s (398645 vs 401430). We concatenate rows, then drop the fully-empty trailer rows (the exports end with blank lines that parse as all-NaN).

In [20]:
df1 = pd.read_csv(F1, dtype=str, keep_default_na=True)
df2 = pd.read_csv(F2, dtype=str, keep_default_na=True)
log(f"raw rows: file1={len(df1)} file2={len(df2)}")
df = pd.concat([df1, df2], ignore_index=True)
df = df.dropna(how='all').reset_index(drop=True)
log(f"stacked after dropping all-NaN trailer rows: {len(df)}")
df.head(3)

[2.2s] raw rows: file1=4860 file2=12732

[2.3s] stacked after dropping all-NaN trailer rows: 17589

,Date Collected,CowID,ClientID,Test,Result,S-N Value,DIM,DSLB
0,05/29/2025,21497,398645,Pregnancy Test - Milk,Pregnant,0.704,157,0
1,05/29/2025,21721,398645,Pregnancy Test - Milk,Pregnant,0.79,155,113
2,05/29/2025,14269,398645,Pregnancy Test - Milk,Pregnant,POS,281,0

## Step 2 — Clean keys (`Date Collected`, `CowID`, `ClientID`, `DIM`, `DSLB`, `S-N Value`)

- `Date Collected` has a leading vertical-tab (`\x0b`, visible in raw bytes). Strip all control chars (`[\x00-\x1f\x7f]`) and whitespace.
- Drop rows missing `Date Collected` / `CowID` / `ClientID` (needed for cow history + `combined_cow`).
- `DIM` / `DSLB` → numeric; drop rows with missing `DSLB` (cannot derive `breeding_date`).
- `S-N Value` kept as **string** on purpose: many `Pregnant` rows in the 398645 file carry the literal value `POS` instead of a number; old data was all-numeric but we must not coerce `POS` to NaN.
- `Result` in new data includes `Not Tested` (52 rows) which did not exist in old data — kept as-is; Cell-54 has no rule for it so those events resolve to `NaN` (see QC step).

In [21]:
# control-char strip (\x0b etc.)
df['Date Collected'] = (
    df['Date Collected'].astype(str)
      .str.replace(r'[\x00-\x1f\x7f]+', '', regex=True)
      .str.strip()
)
df['Date Collected'] = df['Date Collected'].replace({'': np.nan, 'nan': np.nan, 'NaT': np.nan, 'None': np.nan})
for c in ['CowID', 'ClientID']:
    df[c] = df[c].astype(str).str.strip().replace({'': np.nan, 'nan': np.nan, 'None': np.nan})
df = df[df['Date Collected'].notna() & df['CowID'].notna() & df['ClientID'].notna()].copy()

df['DIM'] = pd.to_numeric(df['DIM'], errors='coerce')
df['DSLB'] = pd.to_numeric(df['DSLB'], errors='coerce')
log(f"DSLB NaN={int(df['DSLB'].isna().sum())}, DIM NaN={int(df['DIM'].isna().sum())}")
df = df[df['DSLB'].notna()].copy()
df['S-N Value'] = df['S-N Value'].astype(str).str.strip().replace({'nan': np.nan, '': np.nan, 'None': np.nan})
log(f"after key cleaning: {len(df)} rows")
print(df['Result'].value_counts(dropna=False))

[7.3s] DSLB NaN=0, DIM NaN=0
[7.4s] after key cleaning: 17588 rows
Result
Pregnant      14040
Open           1797
Re-Check       1699
Not Tested       52
Name: count, dtype: int64

## Step 3 — Derive `date_collected`, `breeding_date`, `combined_cow`, `year/month/day`

Mirrors phenotype Cell 6 plus the pre-step that built `unique_combination_cleaned.csv`:
- `date_collected_dt = pd.to_datetime(Date Collected)`; `date_collected` string kept as `M/D/YYYY` (no leading zeros) to match the manual file.
- `breeding_date = date_collected_dt − DSLB days` (timedelta). Check: `3/4/2022 − 35d = 1/28/2022`.
- `combined_cow = f"{CowID_int}.0{ClientID_int}.0"` → `1 + 392159 = 1.0392159.0`; `1000 + 401430 = 1000.0401430.0`. Integer-cast via `int(float(x))` so `"1000.0"` inputs also work.
- `year/month/day/month_day` from `breeding_date` (Cell 6).

In [22]:
df['date_collected_dt'] = pd.to_datetime(df['Date Collected'], format='mixed', errors='coerce')
log(f"date parse failures: {int(df['date_collected_dt'].isna().sum())}")
df = df[df['date_collected_dt'].notna()].copy()
df['breeding_date'] = df['date_collected_dt'] - pd.to_timedelta(df['DSLB'].astype(int), unit='D')

def build_combined(cow, cli):
    try: cow_s = str(int(float(str(cow).strip())))
    except Exception: cow_s = str(cow).strip()
    try: cli_s = str(int(float(str(cli).strip())))
    except Exception: cli_s = str(cli).strip()
    return f"{cow_s}.0{cli_s}.0"
df['combined_cow'] = [build_combined(a, b) for a, b in zip(df['CowID'].values, df['ClientID'].values)]

df['date_collected'] = df['date_collected_dt'].dt.strftime('%-m/%-d/%Y')
df['Date Collected'] = df['date_collected']  # canonical cleaned form
# Cell 6
df['year'] = df['breeding_date'].dt.year
df['month'] = df['breeding_date'].dt.month
df['day'] = df['breeding_date'].dt.day
df['month_day'] = df['breeding_date'].dt.strftime('%m-%d')
log(f"cows={df['combined_cow'].nunique()}, breeding {df['breeding_date'].min().date()}..{df['breeding_date'].max().date()}")
df[['Date Collected','CowID','ClientID','combined_cow','date_collected','breeding_date','DSLB','year','month','day']].head(3)

[9.3s] date parse failures: 0

[9.7s] cows=8586, breeding 2024-08-21..2026-05-21

,Date Collected,CowID,ClientID,combined_cow,date_collected,breeding_date,DSLB,year,month,day
0,5/29/2025,21497,398645,21497.0398645.0,5/29/2025,2025-05-29,0,2025,5,29
1,5/29/2025,21721,398645,21721.0398645.0,5/29/2025,2025-02-05,113,2025,2,5
2,5/29/2025,14269,398645,14269.0398645.0,5/29/2025,2025-05-29,0,2025,5,29

## Step 4 — Breeding-event clustering (phenotype Cell 7, vectorized)

**Original Cell-7 logic (quoted for traceability):** group by `(combined_cow, year, month)`; within each group `date_diff = day.diff()`; `is_new_event = (date_diff >= 2).fillna(True)`; `cluster = is_new_event.cumsum()`; `adj_final_breeding = min(breeding_date)` per cluster; `breed_event_id = cow_year_month_cluster` if >1 cluster else `cow_year_month` (no suffix).

**Two deliberate, documented choices:**
1. *Sort* each `(cow, year, month)` group by `breeding_date` before `.diff()`. The notebook relied on input order; sorting makes the result deterministic and matches the intent (re-breeds 1 day apart stay together, ≥2 days split).
2. *Vectorize* the loop (`sort → groupby.diff → cumsum → groupby.transform('min')`) — identical output, ~2 s instead of >60 s for ~11k groups. `nclus = nunique(cluster)` per group reproduces the with/without-suffix branch.

Known format difference vs the manual file: faithful Cell 7 leaves ~95% of IDs **without** a cluster suffix (`cow_year_month`), while `3_16_26_manual_annotation.csv` always has one (`cow_year_month_cluster`). That is expected from the chosen Cell-7 branch — see QC step.

In [23]:
# Faithful-but-vectorized Cell 7. Compare with the loop quoted above.
df = df.sort_values(['combined_cow', 'year', 'month', 'breeding_date']).reset_index(drop=True)
g = df.groupby(['combined_cow', 'year', 'month'], sort=False)
df['date_diff'] = g['day'].diff()
df['check_new_event'] = (df['date_diff'] >= 4) | df['date_diff'].isna()
df['cluster'] = g['check_new_event'].cumsum()
df['adj_final_breeding'] = df.groupby(['combined_cow', 'year', 'month', 'cluster'], sort=False)['breeding_date'].transform('max')
df['nclus'] = df.groupby(['combined_cow', 'year', 'month'], sort=False)['cluster'].transform('nunique')
base = df['combined_cow'].astype(str) + '_' + df['year'].astype(str) + '_' + df['month'].astype(str)
df['breed_event_id'] = base + np.where(df['nclus'] > 1, '_' + df['cluster'].astype(str), '')
df = df.drop(columns=['nclus'])
log(f"cell7 done: rows={len(df)}, events={df['breed_event_id'].nunique()}")
print((df['breed_event_id'].str.count('_') + 1).value_counts().rename(index={3: '3-part (no suffix)', 4: '4-part (with suffix)'}))
df[df['combined_cow'] == '10010.0401430.0'][['breeding_date','adj_final_breeding','day','breed_event_id','Result','DSLB']].head(10)

[15.6s] cell7 done: rows=17588, events=11386
breed_event_id
3-part (no suffix)      17255
4-part (with suffix)      333
Name: count, dtype: int64

,breeding_date,adj_final_breeding,day,breed_event_id,Result,DSLB
0,2025-05-21,2025-05-22,21,10010.0401430.0_2025_5,Pregnant,91
1,2025-05-22,2025-05-22,22,10010.0401430.0_2025_5,Pregnant,35
2,2025-05-22,2025-05-22,22,10010.0401430.0_2025_5,Re-Check,70
3,2025-05-22,2025-05-22,22,10010.0401430.0_2025_5,Re-Check,77
4,2025-05-22,2025-05-22,22,10010.0401430.0_2025_5,Re-Check,84

## Step 5 — `ai_id` (phenotype Cell 13)

Per cow, rank distinct `adj_final_breeding` values chronologically `1..n`. Vectorized as `groupby('combined_cow')['adj_final_breeding'].rank(method='dense')` — identical to the notebook's `sorted(unique) → {date: i+1}` loop.

In [24]:
df['adj_final_breeding'] = pd.to_datetime(df['adj_final_breeding'])
df['ai_id'] = df.groupby('combined_cow', sort=False)['adj_final_breeding'].rank(method='dense').astype(int)
log('ai_id done')
df[['combined_cow','adj_final_breeding','ai_id','breed_event_id']].head(8)

[23.2s] ai_id done

      combined_cow adj_final_breeding  ai_id          breed_event_id
0  10010.0401430.0         2025-05-22      1  10010.0401430.0_2025_5
1  10010.0401430.0         2025-05-22      1  10010.0401430.0_2025_5
2  10010.0401430.0         2025-05-22      1  10010.0401430.0_2025_5
3  10010.0401430.0         2025-05-22      1  10010.0401430.0_2025_5
4  10010.0401430.0         2025-05-22      1  10010.0401430.0_2025_5
5  10011.0401430.0         2025-05-08      1  10011.0401430.0_2025_5
6  10011.0401430.0         2025-05-08      1  10011.0401430.0_2025_5
7  10011.0401430.0         2025-05-08      1  10011.0401430.0_2025_5

## Step 6 — `sample_id` (phenotype Cell 15)

Per `(combined_cow, ai_id)`, rank distinct `date_collected` values chronologically `1..n` after sorting by `date_collected`. Vectorized dense rank — identical to the notebook loop.

In [25]:
df['sample_id'] = df.groupby(['combined_cow', 'ai_id'], sort=False)['date_collected_dt'].rank(method='dense').astype(int)
log('sample_id done')
df[['combined_cow','ai_id','date_collected','sample_id']].head(8)

[33.5s] sample_id done

      combined_cow  ai_id date_collected  sample_id
0  10010.0401430.0      1      8/20/2025          5
1  10010.0401430.0      1      6/26/2025          1
2  10010.0401430.0      1      7/31/2025          2
3  10010.0401430.0      1       8/7/2025          3
4  10010.0401430.0      1      8/14/2025          4
5  10011.0401430.0      1      6/12/2025          1
6  10011.0401430.0      1      7/17/2025          2
7  10011.0401430.0      1      7/24/2025          3

## Step 7 — `sample_class` (phenotype Cell 17)

Per `breed_event_id`: `sample_id == 1 → first`; `== max → last`; else `intermediate`. Vectorized with `groupby.transform('max')`.

In [26]:
mx = df.groupby('breed_event_id', sort=False)['sample_id'].transform('max')
df['sample_class'] = np.where(df['sample_id'] == 1, 'first', np.where(df['sample_id'] == mx, 'last', 'intermediate'))
log(str(df['sample_class'].value_counts().to_dict()))
df[['breed_event_id','sample_id','sample_class','Result']].head(10)

[51.2s] {'first': 11386, 'last': 5151, 'intermediate': 1051}

           breed_event_id  sample_id  sample_class    Result
0  10010.0401430.0_2025_5          5          last  Pregnant
1  10010.0401430.0_2025_5          1         first  Pregnant
2  10010.0401430.0_2025_5          2  intermediate  Re-Check
3  10010.0401430.0_2025_5          3  intermediate  Re-Check
4  10010.0401430.0_2025_5          4  intermediate  Re-Check
5  10011.0401430.0_2025_5          1         first  Pregnant
6  10011.0401430.0_2025_5          2  intermediate  Re-Check
7  10011.0401430.0_2025_5          3  intermediate  Re-Check
8  10011.0401430.0_2025_5          4          last  Pregnant
9  10016.0401430.0_2025_4          2          last  Pregnant

## Step 8 — `final_resolved` (phenotype Cell 54, latest fixed `resolve_cow_history`)

Applied verbatim, including the `Pregant_with_rc` spelling. Per cow (events in chronological order):

| n | condition | `final_resolved` |
|---|-----------|------------------|
| 1 | — | the single `Result` |
| >1, ends `Pregnant` | first `Pregnant`, has `Open` | `preg_open_preg` |
| >1, ends `Pregnant` | first `Pregnant`, has `Re-Check` | `Pregant_with_rc` |
| >1, ends `Pregnant` | first `Pregnant`, else | `Pregnant` |
| >1, ends `Pregnant` | first `Re-Check` | `rc_preg` |
| >1, ends `Pregnant` | first `Open` | `open_to_preg` |
| >1, ends `Open` | has `Pregnant` | `loss` |
| >1, ends `Open` | first `Re-Check` | `rc_open` |
| >1, ends `Open` | else | `Open` |
| >1, ends `Re-Check` | has `Pregnant` | `preg_to_rc_unresolved` |
| >1, ends `Re-Check` | has `Open` | `open_to_rc_unresolved` |
| >1, ends `Re-Check` | else | `rc_unresolved` |

**Gap overrides** (`curr` → next `adj_final_breeding`): single-event cows ending `Re-Check` → `rc_unresolved`, ending `Open` with any `Pregnant` → `loss_2_open`; multi-event non-last events with gap `<300` and last ≠ `Open` map all-`Pregnant` → `preg_loss_rebred`, `Pregnant`+`Re-Check` → `rc_preg_loss_rebred`, all-`Re-Check` → `rc_rebred` (plus single-sample rebred fixes); gap `>=300` with last `Re-Check` → `rc_unresolved_>_1_bred`; last event ending `Re-Check` → `rc_unresolved_>_1_bred`, ending `Open` with `Pregnant` → `loss_2_open`.

`Not Tested` has no rule and stays `NaN` (see QC). Implementation below loops per cow like the notebook but avoids `groupby.apply` overhead (uses `groupby.indices` + vectorized masks).

In [27]:
df['final_resolved'] = None
df = df.sort_values(['combined_cow', 'adj_final_breeding', 'sample_id']).reset_index(drop=True)

def resolve_cow_history_inline(cow, idx):
    """Cell-54 logic for one cow; writes directly into df via .loc."""
    sub = df.loc[idx].sort_values(['adj_final_breeding', 'sample_id'])
    bed = sub.groupby('breed_event_id', sort=False)['adj_final_breeding'].min().sort_values()
    events = bed.index.tolist()
    emin = bed.to_dict()
    n_events = len(events)
    for i, eid in enumerate(events):
        m = df.index.isin(idx) & (df['breed_event_id'].values == eid)
        ev_rows = df.loc[m].sort_values('sample_id')
        samples = ev_rows['Result'].tolist()
        n = len(samples)
        if n == 0:
            continue
        first, last = samples[0], samples[-1]
        resolved = None
        if n == 1:
            resolved = first
        else:
            if last == 'Pregnant':
                if first == 'Pregnant':
                    if 'Open' in samples: resolved = 'preg_open_preg'
                    elif 'Re-Check' in samples: resolved = 'Pregant_with_rc'
                    else: resolved = 'Pregnant'
                elif first == 'Re-Check': resolved = 'rc_preg'
                elif first == 'Open': resolved = 'open_to_preg'
            elif last == 'Open':
                if 'Pregnant' in samples: resolved = 'loss'
                elif first == 'Re-Check': resolved = 'rc_open'
                else: resolved = 'Open'
            elif last == 'Re-Check':
                if 'Pregnant' in samples: resolved = 'preg_to_rc_unresolved'
                elif 'Open' in samples: resolved = 'open_to_rc_unresolved'
                else: resolved = 'rc_unresolved'
        if n_events == 1:
            if last == 'Re-Check': resolved = 'rc_unresolved'
            elif last == 'Open' and 'Pregnant' in samples: resolved = 'loss_2_open'
        else:
            if i < n_events - 1:
                gap = (emin[events[i+1]] - emin[eid]).days
                if gap < 300:
                    if last != 'Open':
                        if all(r == 'Pregnant' for r in samples): resolved = 'preg_loss_rebred'
                        elif 'Pregnant' in samples and 'Re-Check' in samples: resolved = 'rc_preg_loss_rebred'
                        elif all(r == 'Re-Check' for r in samples): resolved = 'rc_rebred'
                        elif n == 1 and last == 'Re-Check': resolved = 'rc_rebred'
                        elif n == 1 and last == 'Pregnant': resolved = 'preg_loss_rebred'
                elif gap >= 300:
                    if last == 'Re-Check': resolved = 'rc_unresolved_>_1_bred'
            else:
                if last == 'Re-Check': resolved = 'rc_unresolved_>_1_bred'
                elif last == 'Open' and 'Pregnant' in samples: resolved = 'loss_2_open'
        df.loc[m, 'final_resolved'] = resolved

cow_groups = df.groupby('combined_cow', sort=False).indices
log(f"resolving {len(cow_groups)} cows ...")
for k, (cow, idx) in enumerate(cow_groups.items(), 1):
    resolve_cow_history_inline(cow, idx)
    if k % 2000 == 0:
        log(f"resolved {k}/{len(cow_groups)} cows")
log(f"resolve done; unresolved(NaN)={int(df['final_resolved'].isna().sum())}")
print(df['final_resolved'].value_counts(dropna=False).head(30))

[62.8s] resolving 8586 cows ...
[77.9s] resolved 2000/8586 cows
[92.6s] resolved 4000/8586 cows
[107.3s] resolved 6000/8586 cows
[121.1s] resolved 8000/8586 cows
[125.6s] resolve done; unresolved(NaN)=56
final_resolved
Pregnant                  11904
Open                       1475
Pregant_with_rc            1327
rc_preg                     757
preg_loss_rebred            745
rc_open                     289
loss                        246
rc_unresolved               191
loss_2_open                 161
rc_unresolved_>_1_bred      158
rc_rebred                   144
open_to_preg                 95
None                         56
rc_preg_loss_rebred          28
Not Tested                    9
preg_open_preg                3
Name: count, dtype: int64

## Step 9 — Format output like `3_16_26_manual_annotation.csv`

Exact 23-column order: `Date Collected, Date Received, CowID, Date Sent, Date Approved, ClientID, ProjectNo, Test, S-N Value, DIM, combined_cow, date_collected, year, adj_final_breeding, DSLB, breed_event_id, ai_id, sample_id, sample_class, Result, final_resolved, first_sample_rc, rc_resolved_open`.
- `Date Received/Sent/Approved`, `ProjectNo`, `first_sample_rc`, `rc_resolved_open` = NaN (absent from new raw files; last two per user choice).
- `adj_final_breeding` formatted `M/D/YYYY` (no leading zeros) like the manual file.
- Sorted by `combined_cow, adj_final_breeding, date_collected` like the manual file.

In [28]:
for c in ['Date Received', 'Date Sent', 'Date Approved', 'ProjectNo']:
    df[c] = np.nan
df['first_sample_rc'] = np.nan
df['rc_resolved_open'] = np.nan
df['adj_str'] = pd.to_datetime(df['adj_final_breeding']).dt.strftime('%-m/%-d/%Y')

def clean_id(x):
    try:
        f = float(str(x))
        return str(int(f)) if f.is_integer() else str(x)
    except Exception:
        return str(x)
df['CowID'] = df['CowID'].apply(clean_id)
df['ClientID'] = df['ClientID'].apply(clean_id)

out = pd.DataFrame({
    'Date Collected': df['Date Collected'],
    'Date Received': df['Date Received'],
    'CowID': df['CowID'],
    'Date Sent': df['Date Sent'],
    'Date Approved': df['Date Approved'],
    'ClientID': df['ClientID'],
    'ProjectNo': df['ProjectNo'],
    'Test': df['Test'],
    'S-N Value': df['S-N Value'],
    'DIM': df['DIM'],
    'combined_cow': df['combined_cow'],
    'date_collected': df['date_collected'],
    'year': df['year'],
    'adj_final_breeding': df['adj_str'],
    'DSLB': df['DSLB'],
    'breed_event_id': df['breed_event_id'],
    'ai_id': df['ai_id'],
    'sample_id': df['sample_id'],
    'sample_class': df['sample_class'],
    'Result': df['Result'],
    'final_resolved': df['final_resolved'],
    'first_sample_rc': df['first_sample_rc'],
    'rc_resolved_open': df['rc_resolved_open'],
})
out['_b'] = pd.to_datetime(df['adj_final_breeding'].values)
out['_c'] = df['date_collected_dt'].values
out = out.sort_values(['combined_cow', '_b', '_c']).drop(columns=['_b', '_c']).reset_index(drop=True)
out.to_csv(OUT, index=False)
log(f"wrote {OUT} rows={len(out)}")
out.head(10)

[282.6s] wrote /home/rajesh/work/ornella/merged_annotation_output.csv rows=17588

,Date Collected,Date Received,CowID,Date Sent,Date Approved,ClientID,ProjectNo,Test,S-N Value,DIM,...,adj_final_breeding,DSLB,breed_event_id,ai_id,sample_id,sample_class,Result,final_resolved,first_sample_rc,rc_resolved_open
0,6/26/2025,NaN,10010,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.56,121,...,5/22/2025,35,10010.0401430.0_2025_5,1,1,first,Pregnant,Pregant_with_rc,NaN,NaN
1,7/31/2025,NaN,10010,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.14,156,...,5/22/2025,70,10010.0401430.0_2025_5,1,2,intermediate,Re-Check,Pregant_with_rc,NaN,NaN
2,8/7/2025,NaN,10010,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.16,163,...,5/22/2025,77,10010.0401430.0_2025_5,1,3,intermediate,Re-Check,Pregant_with_rc,NaN,NaN
3,8/14/2025,NaN,10010,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.229,170,...,5/22/2025,84,10010.0401430.0_2025_5,1,4,intermediate,Re-Check,Pregant_with_rc,NaN,NaN
4,8/20/2025,NaN,10010,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.341,177,...,5/22/2025,91,10010.0401430.0_2025_5,1,5,last,Pregnant,Pregant_with_rc,NaN,NaN
5,6/12/2025,NaN,10011,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.688,282,...,5/8/2025,35,10011.0401430.0_2025_5,1,1,first,Pregnant,Pregant_with_rc,NaN,NaN
6,7/17/2025,NaN,10011,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.237,317,...,5/8/2025,70,10011.0401430.0_2025_5,1,2,intermediate,Re-Check,Pregant_with_rc,NaN,NaN
7,7/24/2025,NaN,10011,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.225,324,...,5/8/2025,77,10011.0401430.0_2025_5,1,3,intermediate,Re-Check,Pregant_with_rc,NaN,NaN
8,7/31/2025,NaN,10011,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.417,331,...,5/8/2025,84,10011.0401430.0_2025_5,1,4,last,Pregnant,Pregant_with_rc,NaN,NaN
9,5/29/2025,NaN,10016,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.619,120,...,4/22/2025,37,10016.0401430.0_2025_4,1,1,first,Pregnant,Pregnant,NaN,NaN

## Step 10 — Verification / QC

1. Column order matches the manual file.
2. Overlap check: cow `10010.0401430.0` (present in both eras, breeding `5/21/2025`) should show the same 5-sample `Pregnant → Re-Check ×3 → Pregnant` sequence resolving to `Pregant_with_rc`.
3. Unresolved (`NaN`) rows should only be `Not Tested`-mixed sequences, which Cell 54 does not cover.
4. `breed_event_id` parts check documents the faithful-Cell-7 suffix behavior.

In [29]:
man_cols = list(pd.read_csv(MANUAL_REF, nrows=2).columns)
print('columns match manual:', list(out.columns) == man_cols)
print('out shape:', out.shape)
print(out['final_resolved'].value_counts(dropna=False))
print()
print('--- overlap cow 10010.0401430.0 ---')
print(out[out['combined_cow'] == '10010.0401430.0'][['Date Collected','DSLB','adj_final_breeding','breed_event_id','ai_id','sample_id','sample_class','Result','final_resolved']].to_string(index=False))
print()
print('--- unresolved patterns (expect only Not Tested mixes) ---')
un = out[out['final_resolved'].isna()]
print('unresolved rows:', len(un))
print(un.groupby('breed_event_id')['Result'].apply(list).apply(tuple).value_counts().head(10))
print()
print('--- breed_event_id suffix check (faithful Cell 7) ---')
print((out['breed_event_id'].str.count('_') + 1).value_counts().rename(index={3: '3-part (no suffix)', 4: '4-part (with suffix)'}))
print(f"total runtime: {time.time()-T0:.1f}s")

columns match manual: True
out shape: (17588, 23)
final_resolved
Pregnant                  11904
Open                       1475
Pregant_with_rc            1327
rc_preg                     757
preg_loss_rebred            745
rc_open                     289
loss                        246
rc_unresolved               191
loss_2_open                 161
rc_unresolved_>_1_bred      158
rc_rebred                   144
open_to_preg                 95
None                         56
rc_preg_loss_rebred          28
Not Tested                    9
preg_open_preg                3
Name: count, dtype: int64

--- overlap cow 10010.0401430.0 ---
Date Collected  DSLB adj_final_breeding         breed_event_id  ai_id  sample_id sample_class   Result  final_resolved
     6/26/2025    35          5/22/2025 10010.0401430.0_2025_5      1          1        first Pregnant Pregant_with_rc
     7/31/2025    70          5/22/2025 10010.0401430.0_2025_5      1          2 intermediate Re-Check Pregant_with_rc
      8/7/2025    77          5/22/2025 10010.0401430.0_2025_5      1          3 intermediate Re-Check Pregant_with_rc
     8/14/2025    84          5/22/2025 10010.0401430.0_2025_5      1          4 intermediate Re-Check Pregant_with_rc
     8/20/2025    91          5/22/2025 10010.0401430.0_2025_5      1          5         last Pregnant Pregant_with_rc

--- unresolved patterns (expect only Not Tested mixes) ---
unresolved rows: 56
Result
(Not Tested, Pregnant, Pregnant)                        11
(Not Tested, Pregnant)                                   3
(Pregnant, Not Tested)                                   2
(Pregnant, Pregnant, Not Tested)                         2
(Not Tested, Re-Check, Re-Check, Re-Check, Pregnant)     1
(Re-Check, Not Tested)                                   1
Name: count, dtype: int64

--- breed_event_id suffix check (faithful Cell 7) ---
breed_event_id
3-part (no suffix)      17255
4-part (with suffix)      333
Name: count, dtype: int64
total runtime: 287.1s

## Step 11 — Flag cows with breeding events 2–3 days apart

**Definition used (documented assumption).** For each `combined_cow`, sort its distinct raw `breeding_date` values
(`breeding_date = date_collected − DSLB`, recomputed here from the merged output) and take consecutive gaps in days.
A cow is flagged if **any gap is 2 or 3 days**. In `merged_annotation_output.csv` (Cell-7 faithful splits) the
`adj_final_breeding` gaps coincide exactly with the raw gaps (241/241 overlap, verified below), so this also equals
the adj-gap definition. (For reference: in `3_16_26_manual_annotation.csv` the raw gaps contain 241 such cows but the
adj gaps contain 0, because that file's clustering merged 2–3 day re-breeds — min adj gap 27 days.)

**Outputs.**
- `flagged_cows_gap_2_3_days.csv` — **all rows/events** for the flagged cows (original 23 cols + `breeding_date`,
  `raw_gap_to_next_breeding_days`, `is_2_3_day_pair_start`).
- `flagged_cows_gap_2_3_days_summary.csv` — one row per flagged cow (`breeding_date_1/2`, `raw_gap_days`, row/event counts).

In [34]:
# Step 11 — recompute breeding dates from merged output (self-contained: reloads OUT)
import pandas as pd, numpy as np
SRC = OUT  # from Step 0 paths
adf = pd.read_csv("/home/rajesh/work/ornella/merged_annotation_output.csv", dtype=str, keep_default_na=True)
adf['DSLB_n'] = pd.to_numeric(adf['DSLB'], errors='coerce')
adf['dc'] = pd.to_datetime(adf['date_collected'], format='mixed', errors='coerce')
adf['bd'] = adf['dc'] - pd.to_timedelta(adf['DSLB_n'].astype('Int64').astype(float).astype(int), unit='D')
adf['adj'] = pd.to_datetime(adf['adj_final_breeding'], format='mixed', errors='coerce')

gap_summary, flag_cows = [], set()
for cow, g in adf.groupby('combined_cow'):
    bds = sorted(g['bd'].dropna().unique())
    adjs = sorted(g['adj'].dropna().unique())
    for i in range(len(adjs) - 1):
        gap = (adjs[i+1] - adjs[i]).days
        if 2 <= gap <= 3:
            flag_cows.add(cow)
            gap_summary.append({
                'combined_cow': cow,
                'CowID': g['CowID'].iloc[0],
                'ClientID': g['ClientID'].iloc[0],
                'breeding_date_1': adjs[i].strftime('%-m/%-d/%Y'),
                'breeding_date_2': adjs[i+1].strftime('%-m/%-d/%Y'),
                'raw_gap_days': gap,
                'n_rows_cow': len(g),
                'n_breeding_dates': len(bds),
                'n_adj_events': len(adjs),
            })
            break
log(f"flagged cows (raw gap 2-3): {len(flag_cows)}")
# cross-check adj definition
adj_n = 0
for cow in flag_cows:
    u = sorted(adf[adf['combined_cow']==cow]['adj'].dropna().unique())
    if any(2 <= (u[i+1]-u[i]).days <= 3 for i in range(len(u)-1)):
        adj_n += 1
log(f"of those, also adj gap 2-3: {adj_n} (expected 241/241 in merged file)")

sub = adf[adf['combined_cow'].isin(flag_cows)].copy()
sub['breeding_date'] = sub['bd'].dt.strftime('%-m/%-d/%Y')
sub = sub.sort_values(['combined_cow','bd','dc']).reset_index(drop=True)
gap_map = {}
for cow, g in sub.groupby('combined_cow'):
    bds = sorted(g['bd'].dropna().unique())
    for i, b in enumerate(bds):
        gap_map[(cow, b)] = (bds[i+1]-b).days if i < len(bds)-1 else np.nan
sub['raw_gap_to_next_breeding_days'] = [gap_map.get((c,b), np.nan) for c, b in zip(sub['combined_cow'], sub['bd'])]
sub['is_2_3_day_pair_start'] = sub['raw_gap_to_next_breeding_days'].apply(lambda x: 'yes' if pd.notna(x) and 2 <= x <= 3 else '')
ORIG = ['Date Collected','Date Received','CowID','Date Sent','Date Approved','ClientID','ProjectNo','Test','S-N Value','DIM','combined_cow','date_collected','year','adj_final_breeding','DSLB','breed_event_id','ai_id','sample_id','sample_class','Result','final_resolved','first_sample_rc','rc_resolved_open']
sub[ORIG + ['breeding_date','raw_gap_to_next_breeding_days','is_2_3_day_pair_start']].to_csv(
    '/home/rajesh/work/ornella/flagged_cows_gap_2_3_days.csv', index=False)
pd.DataFrame(gap_summary).sort_values('combined_cow').to_csv(
    '/home/rajesh/work/ornella/flagged_cows_gap_2_3_days_summary.csv', index=False)
log(f"wrote flagged main {len(sub)} rows + summary {len(gap_summary)} rows")
sub[sub['combined_cow']=='10126.0401430.0'][ORIG[-8:]+['breeding_date','raw_gap_to_next_breeding_days','is_2_3_day_pair_start']].head(5)

[578.4s] flagged cows (raw gap 2-3): 9
[578.5s] of those, also adj gap 2-3: 9 (expected 241/241 in merged file)
[578.5s] wrote flagged main 42 rows + summary 9 rows

Empty DataFrame
Columns: [breed_event_id, ai_id, sample_id, sample_class, Result, final_resolved, first_sample_rc, rc_resolved_open, breeding_date, raw_gap_to_next_breeding_days, is_2_3_day_pair_start]
Index: []

In [33]:
sub

,Date Collected,Date Received,CowID,Date Sent,Date Approved,ClientID,ProjectNo,Test,S-N Value,DIM,...,final_resolved,first_sample_rc,rc_resolved_open,DSLB_n,dc,bd,adj,breeding_date,raw_gap_to_next_breeding_days,is_2_3_day_pair_start
0,12/31/2025,NaN,10126,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.489,150,...,Pregnant,NaN,NaN,79,2025-12-31,2025-10-13,2025-10-16,10/13/2025,3.0,yes
1,11/20/2025,NaN,10126,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.711,106,...,Pregnant,NaN,NaN,35,2025-11-20,2025-10-16,2025-10-16,10/16/2025,NaN,
2,12/23/2025,NaN,10126,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.29,139,...,Pregnant,NaN,NaN,68,2025-12-23,2025-10-16,2025-10-16,10/16/2025,NaN,
3,8/28/2025,NaN,10159,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.585,150,...,Pregnant,NaN,NaN,40,2025-08-28,2025-07-19,2025-07-21,7/19/2025,2.0,yes
4,10/2/2025,NaN,10159,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.617,183,...,Pregnant,NaN,NaN,73,2025-10-02,2025-07-21,2025-07-21,7/21/2025,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2/12/2026,NaN,9378,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.378,381,...,Pregnant,NaN,NaN,75,2026-02-12,2025-11-29,2025-11-29,11/29/2025,NaN,
734,11/13/2025,NaN,9656,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.497,110,...,preg_loss_rebred,NaN,NaN,35,2025-11-13,2025-10-09,2025-10-09,10/9/2025,75.0,
735,12/23/2025,NaN,9656,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.15,150,...,rc_rebred,NaN,NaN,0,2025-12-23,2025-12-23,2025-12-23,12/23/2025,71.0,
736,4/7/2026,NaN,9656,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.99,257,...,Pregnant,NaN,NaN,34,2026-04-07,2026-03-04,2026-03-06,3/4/2026,2.0,yes
737,5/21/2026,NaN,9656,NaN,NaN,401430,NaN,Pregnancy Test - Milk,1.144,299,...,Pregnant,NaN,NaN,76,2026-05-21,2026-03-06,2026-03-06,3/6/2026,NaN,

## Step 12 — Duplicate / identical IDs

**Documented assumptions (two leading interpretations, both exported).**
No exact full-row duplicates exist in either file, so:

- **(A) Same numeric `CowID` under >1 `ClientID`/`combined_cow`.** In merged data: **1,221 CowIDs → 4,574 rows / 2,442 combined_cows**
  (manual file: 445 CowIDs). Output `cows_duplicate_CowID_across_clients.csv` contains **all events** for those combined IDs,
  plus `n_clients_for_CowID`, `n_combined_for_CowID`.
- **(B) Same `(CowID, Date Collected)` more than once.** In merged data: **124 rows / 62 groups** (manual: 49 groups).
  Output `duplicate_CowID_Date_rows.csv` contains those rows plus `same_combined_cow`
  (`yes-same-test-repeat` = lab repeat on same combined cow, e.g. `12913` on 2/5/2026 with S-N 0.412 vs 0.667;
  `no-cross-client` = collision across clients). The strict subset with same `(combined_cow, Date Collected)` is 20 rows / 10 groups.

In [13]:
# Step 12 — duplicates (self-contained: reloads OUT)
import pandas as pd
ddf = pd.read_csv(OUT, dtype=str, keep_default_na=True)
ORIG = ['Date Collected','Date Received','CowID','Date Sent','Date Approved','ClientID','ProjectNo','Test','S-N Value','DIM','combined_cow','date_collected','year','adj_final_breeding','DSLB','breed_event_id','ai_id','sample_id','sample_class','Result','final_resolved','first_sample_rc','rc_resolved_open']

# (A) CowID across clients
grp = ddf.drop_duplicates(['CowID','ClientID']).groupby('CowID')
multi = [cow for cow, s in grp if s['ClientID'].nunique() > 1]
log(f"multi-client CowIDs: {len(multi)}")
dupA = ddf[ddf['CowID'].isin(multi)].copy()
ncli = ddf.drop_duplicates(['CowID','ClientID']).groupby('CowID')['ClientID'].nunique().to_dict()
ncomb = dupA.groupby('CowID')['combined_cow'].nunique().to_dict()
dupA['n_clients_for_CowID'] = dupA['CowID'].map(ncli)
dupA['n_combined_for_CowID'] = dupA['CowID'].map(ncomb)
dupA = dupA.sort_values(['CowID','combined_cow','date_collected']).reset_index(drop=True)
dupA[ORIG + ['n_clients_for_CowID','n_combined_for_CowID']].to_csv(
    '/home/rajesh/work/ornella/cows_duplicate_CowID_across_clients.csv', index=False)
log(f"wrote dupA {len(dupA)} rows / {dupA['combined_cow'].nunique()} combined_cows")

# (B) duplicate (CowID, Date Collected)
d1 = ddf.duplicated(subset=['CowID','Date Collected'], keep=False)
dupB = ddf[d1].copy()
dupB['same_combined_cow'] = dupB.groupby(['CowID','Date Collected'])['combined_cow'].transform('nunique').apply(
    lambda n: 'yes-same-test-repeat' if n == 1 else 'no-cross-client')
dupB = dupB.sort_values(['CowID','Date Collected','combined_cow']).reset_index(drop=True)
dupB[ORIG + ['same_combined_cow']].to_csv(
    '/home/rajesh/work/ornella/duplicate_CowID_Date_rows.csv', index=False)
d2n = int(ddf.duplicated(subset=['combined_cow','Date Collected'], keep=False).sum())
log(f"wrote dupB {len(dupB)} rows in {dupB.groupby(['CowID','Date Collected']).ngroups} groups; same-combined subset: {d2n} rows")
dupB.head(4)

[228.4s] multi-client CowIDs: 1221
[228.5s] wrote dupA 4574 rows / 2442 combined_cows
[228.5s] wrote dupB 124 rows in 62 groups; same-combined subset: 20 rows

,Date Collected,Date Received,CowID,Date Sent,Date Approved,ClientID,ProjectNo,Test,S-N Value,DIM,...,DSLB,breed_event_id,ai_id,sample_id,sample_class,Result,final_resolved,first_sample_rc,rc_resolved_open,same_combined_cow
0,2/5/2026,NaN,12913,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.412,396,...,109,12913.0401430.0_2025_10,4,7,last,Pregnant,Pregant_with_rc,NaN,NaN,yes-same-test-repeat
1,2/5/2026,NaN,12913,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.667,396,...,109,12913.0401430.0_2025_10,4,7,last,Pregnant,Pregant_with_rc,NaN,NaN,yes-same-test-repeat
2,2/19/2026,NaN,15013,NaN,NaN,398645,NaN,Pregnancy Test - Milk,0.24,217,...,92,15013.0398645.0_2025_11,1,1,first,Re-Check,rc_unresolved,NaN,NaN,no-cross-client
3,2/19/2026,NaN,15013,NaN,NaN,401430,NaN,Pregnancy Test - Milk,0.648,91,...,38,15013.0401430.0_2026_1,1,1,first,Pregnant,Pregnant,NaN,NaN,no-cross-client

## Step 13 — Verification of flagged / duplicate outputs

Checks: file sizes, flagged count (expect 241 cows / 738 rows), dupA (1,221 CowIDs / 4,574 rows), dupB (124 rows / 62 groups),
plus a spot-check of the `10126.0401430.0` 3-day pair and a true lab-repeat example (`12913` on 2/5/2026).

In [14]:
import pandas as pd, os
for p in ['/home/rajesh/work/ornella/flagged_cows_gap_2_3_days.csv',
          '/home/rajesh/work/ornella/flagged_cows_gap_2_3_days_summary.csv',
          '/home/rajesh/work/ornella/cows_duplicate_CowID_across_clients.csv',
          '/home/rajesh/work/ornella/duplicate_CowID_Date_rows.csv']:
    d = pd.read_csv(p)
    print(os.path.basename(p), 'rows=', len(d), 'cols=', len(d.columns))
print()
f = pd.read_csv('/home/rajesh/work/ornella/flagged_cows_gap_2_3_days_summary.csv')
print('summary cows:', len(f), '| gap values:', sorted(f['raw_gap_days'].unique()))
print(f.head(3).to_string(index=False))
print()
d = pd.read_csv('/home/rajesh/work/ornella/duplicate_CowID_Date_rows.csv')
print('dupB groups:', d.groupby(['CowID','Date Collected']).ngroups, '| same-combined repeats:', (d['same_combined_cow']=='yes-same-test-repeat').sum())
print(d[d['CowID'].astype(str)=='12913'][['CowID','Date Collected','combined_cow','S-N Value','DIM','DSLB','Result']].to_string(index=False))

flagged_cows_gap_2_3_days.csv rows= 738 cols= 26
flagged_cows_gap_2_3_days_summary.csv rows= 241 cols= 9
cows_duplicate_CowID_across_clients.csv rows= 4574 cols= 25
duplicate_CowID_Date_rows.csv rows= 124 cols= 24

summary cows: 241 | gap values: [np.int64(2), np.int64(3)]
   combined_cow  CowID  ClientID breeding_date_1 breeding_date_2  raw_gap_days  n_rows_cow  n_breeding_dates  n_adj_events
10126.0401430.0  10126    401430      10/13/2025      10/16/2025             3           3                 2             1
10159.0401430.0  10159    401430       7/19/2025       7/21/2025             2           2                 2             1
10374.0401430.0  10374    401430      11/24/2025      11/27/2025             3           3                 2             1

dupB groups: 62 | same-combined repeats: 20
 CowID Date Collected    combined_cow S-N Value  DIM  DSLB   Result
 12913       2/5/2026 12913.0401430.0     0.412  396   109 Pregnant
 12913       2/5/2026 12913.0401430.0     0.667  396   109 Pregnant